[phases.setup]
nixPkgs = [
    "poppler_utils",
    "libreoffice",
    "qpdf",
    "python3"
]

[phases.build]
cmds = [
    "npm install",
    "cd backend && python3 -m venv venv",
    "cd backend && ./venv/bin/pip install --no-cache-dir pdf2docx PyMuPDF python-pptx"
]

[start]
cmd = "cd backend && npm start"
